server:
  host: "localhost"
  listen_port: "8080"

resources:
  - name: example
    endpoint: /example
    destination_url: "https://10.10.10.2"
    access:
      - name: supername
        key: supersecurething
